-- Schema for The Big Skill Challenge
-- Designed for Microsoft SQL Server

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) UNIQUE NOT NULL,
    Phone NVARCHAR(20),
    Country NVARCHAR(100),
    PasswordHash NVARCHAR(MAX) NOT NULL,
    IsEmailVerified BIT DEFAULT 0,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE EmailVerificationOTP (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    OtpCode NVARCHAR(10) NOT NULL,
    ExpiresAt DATETIME2 NOT NULL,
    IsUsed BIT DEFAULT 0
);

CREATE TABLE Competitions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX),
    StartDate DATETIME2 NOT NULL,
    EndDate DATETIME2 NOT NULL,
    IsPublished BIT DEFAULT 0,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE QuizQuestions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    QuestionText NVARCHAR(MAX) NOT NULL,
    CorrectAnswer NVARCHAR(MAX) NOT NULL,
    OptionsJson NVARCHAR(MAX) NOT NULL -- Store options as ["A", "B", "C"]
);

CREATE TABLE CompetitionQuestions (
    CompetitionId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Competitions(Id) ON DELETE CASCADE,
    QuizQuestionId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES QuizQuestions(Id) ON DELETE CASCADE,
    PRIMARY KEY (CompetitionId, QuizQuestionId)
);

CREATE TABLE QuizSessions (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) ON DELETE NO ACTION,
    CompetitionId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Competitions(Id) ON DELETE NO ACTION,
    StartedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CompletedAt DATETIME2 NULL,
    IsSuccessful BIT DEFAULT 0,
    IsTimedOut BIT DEFAULT 0,
    CONSTRAINT UQ_User_Competition UNIQUE (UserId, CompetitionId) -- 1 attempt only
);

CREATE TABLE QuizAnswers (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    QuizSessionId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES QuizSessions(Id) ON DELETE CASCADE,
    QuizQuestionId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES QuizQuestions(Id) ON DELETE NO ACTION,
    SubmittedAnswer NVARCHAR(MAX) NOT NULL,
    IsCorrect BIT NOT NULL,
    SubmittedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Entries (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    CompetitionId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Competitions(Id) ON DELETE CASCADE,
    SubmissionText NVARCHAR(MAX) NOT NULL,
    SubmittedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE AIValidationResults (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    EntryId UNIQUEIDENTIFIER UNIQUE FOREIGN KEY REFERENCES Entries(Id) ON DELETE CASCADE,
    IsValid BIT NOT NULL,
    WordCount INT NOT NULL,
    SimilarityScore FLOAT NOT NULL,
    StatusMessage NVARCHAR(1000),
    ValidatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);

CREATE TABLE AuditLogs (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Action NVARCHAR(100) NOT NULL,
    Subsystem NVARCHAR(100) NOT NULL,
    Details NVARCHAR(MAX),
    Timestamp DATETIME2 DEFAULT SYSUTCDATETIME()
);
